name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: |
        sudo apt install mingw-w64 mingw-w64-tools
        sudo apt install openjdk-8-jdk
        sudo apt install ffmpeg libsdl2-2.0-0
        sudo apt install gcc git pkg-config meson ninja-build libavcodec-dev libavformat-dev libavutil-dev libsdl2-dev
    - name: Build
      run: make -f Makefile.CrossWindows
    - name: check
      run: ls dist
